ALTER TABLE bookings DROP COLUMN IF EXISTS quantity;

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS total_price NUMERIC(19, 2) NOT NULL;

ALTER TABLE bookings ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE bookings ALTER COLUMN created_at SET NOT NULL;