openapi: 3.1.0
info:
  title: Notification Service API
  description: |
    This service handles sending email notifications based on Kafka events.

    ⚡ **Note:** This service does not expose public HTTP endpoints.

    It listens to Kafka events such as `payment.succeeded` and `ticket.qr.generated`, and sends appropriate email notifications to users.
  contact:
    name: Dario A. Plaza Leon
    url: https://plazaleon.tech
    email: contact@plazaleon.tech
  version: 1.0.0
servers:
- url: http://localhost:8085
  description: Generated server url
paths: {}
components: {}
